name: Lighthouse A11y CI
on: [push, pull_request]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        working-directory: ./web-components
        run: npm ci
        
      - name: Build project
        working-directory: ./web-components
        run: npm run build
        
      - name: Start preview server
        working-directory: ./web-components
        run: npm run preview -- --host 0.0.0.0 --port 4173 &
        
      - name: Wait for server
        run: sleep 5
        
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: http://localhost:4173
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: './lighthouserc.json'
          
      - name: Save Lighthouse report
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-reports
          path: '.lighthouseci'